// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['app_base']['App']['GetConfig']();
}

export function GetMusicPlayerUrl(arg1, arg2) {
  return window['go']['app_base']['App']['GetMusicPlayerUrl'](arg1, arg2);
}

export function GetStorage(arg1) {
  return window['go']['app_base']['App']['GetStorage'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['app_base']['App']['OpenDirectoryDialog'](arg1);
}

export function RemoveStorage(arg1) {
  return window['go']['app_base']['App']['RemoveStorage'](arg1);
}

export function SetStorage(arg1, arg2) {
  return window['go']['app_base']['App']['SetStorage'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app_base']['App']['Startup'](arg1);
}
