// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app_base} from '../models';
import {context} from '../models';

export function GetConfig():Promise<app_base.Config>;

export function GetMusicPlayerUrl(arg1:string,arg2:string):Promise<string>;

export function GetStorage(arg1:string):Promise<string>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function RemoveStorage(arg1:string):Promise<void>;

export function SetStorage(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
