// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app_bili} from '../models';
import {bb_client} from '../models';
import {context} from '../models';

export function DownloadMusic(arg1:app_bili.DownloadMusicParams):Promise<string>;

export function GetConfig():Promise<app_bili.Config>;

export function GetMusicPlayerUrl(arg1:string,arg2:string):Promise<string>;

export function GetOpenMusicOrderList(arg1:string):Promise<Array<app_bili.MusicOrderItem>>;

export function InitConfig():Promise<void>;

export function Search(arg1:bb_client.SearchParams):Promise<app_bili.SearchResponse>;

export function SearchDetail(arg1:string,arg2:string):Promise<app_bili.SearchItem>;

export function Startup(arg1:context.Context):Promise<void>;
