// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadMusic(arg1) {
  return window['go']['app_bili']['App']['DownloadMusic'](arg1);
}

export function ExportConfig() {
  return window['go']['app_bili']['App']['ExportConfig']();
}

export function GetConfig() {
  return window['go']['app_bili']['App']['GetConfig']();
}

export function GetMusicFile(arg1) {
  return window['go']['app_bili']['App']['GetMusicFile'](arg1);
}

export function GetOpenMusicOrderList(arg1) {
  return window['go']['app_bili']['App']['GetOpenMusicOrderList'](arg1);
}

export function InitConfig(arg1) {
  return window['go']['app_bili']['App']['InitConfig'](arg1);
}

export function Search(arg1) {
  return window['go']['app_bili']['App']['Search'](arg1);
}

export function SearchDetail(arg1) {
  return window['go']['app_bili']['App']['SearchDetail'](arg1);
}
