// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadMusic(arg1) {
  return window['go']['app_bili']['App']['DownloadMusic'](arg1);
}

export function GetConfig() {
  return window['go']['app_bili']['App']['GetConfig']();
}

export function GetMusicPlayerUrl(arg1, arg2) {
  return window['go']['app_bili']['App']['GetMusicPlayerUrl'](arg1, arg2);
}

export function GetOpenMusicOrderList(arg1) {
  return window['go']['app_bili']['App']['GetOpenMusicOrderList'](arg1);
}

export function InitConfig() {
  return window['go']['app_bili']['App']['InitConfig']();
}

export function Search(arg1) {
  return window['go']['app_bili']['App']['Search'](arg1);
}

export function SearchDetail(arg1, arg2) {
  return window['go']['app_bili']['App']['SearchDetail'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app_bili']['App']['Startup'](arg1);
}
