// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bb_type} from '../models';
import {app_bili} from '../models';
import {httputil} from '../models';

export function DownloadMusic(arg1:bb_type.DownloadMusicParams):Promise<string>;

export function ExportConfig():Promise<app_bili.Config>;

export function GetConfig():Promise<any>;

export function GetMusicFile(arg1:string):Promise<httputil.ReverseProxy>;

export function GetOpenMusicOrderList(arg1:string):Promise<any>;

export function InitConfig(arg1:boolean):Promise<void>;

export function Search(arg1:bb_type.SearchParams):Promise<bb_type.SearchResponse>;

export function SearchDetail(arg1:string):Promise<bb_type.SearchItem>;
