// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {bb_client} from '../models';

export function DownloadMusic(arg1:app.DownloadMusicParams,arg2:app.AuthParams):Promise<string>;

export function GetConfig():Promise<app.AppConfig>;

export function GetJsonOrigin(arg1:string):Promise<Array<app.MusicOrderItem>>;

export function GetSignData():Promise<bb_client.SignData>;

export function GetSpiData():Promise<bb_client.SpiData>;

export function GetStorage(arg1:string):Promise<string>;

export function GetVideoDetail(arg1:bb_client.GetVideoDetailParams,arg2:app.AuthParams):Promise<bb_client.VideoDetailResponse>;

export function GetVideoUrl(arg1:bb_client.GetVideoUrlParams,arg2:app.AuthParams):Promise<bb_client.VideoUrlResponse>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function RemoveStorage(arg1:string):Promise<void>;

export function Search(arg1:bb_client.SearchParams,arg2:app.AuthParams):Promise<bb_client.SearchResponse>;

export function SetStorage(arg1:string,arg2:string):Promise<void>;
