// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSignData() {
  return window['go']['app']['App']['GetSignData']();
}

export function GetVideoDetail(arg1) {
  return window['go']['app']['App']['GetVideoDetail'](arg1);
}

export function GetVideoUrl(arg1) {
  return window['go']['app']['App']['GetVideoUrl'](arg1);
}

export function LoadSignData() {
  return window['go']['app']['App']['LoadSignData']();
}

export function Search(arg1) {
  return window['go']['app']['App']['Search'](arg1);
}

export function UpdateClientSignData(arg1) {
  return window['go']['app']['App']['UpdateClientSignData'](arg1);
}
