// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {biliClient} from '../models';

export function GetSignData():Promise<biliClient.SignData>;

export function GetVideoDetail(arg1:biliClient.GetVideoDetailParams):Promise<biliClient.VideoDetailResponse>;

export function GetVideoUrl(arg1:biliClient.GetVideoUrlParams):Promise<biliClient.VideoUrlResponse>;

export function LoadSignData():Promise<biliClient.SignData>;

export function Search(arg1:biliClient.SearchParams):Promise<biliClient.SearchResponse>;

export function UpdateClientSignData(arg1:biliClient.SignData):Promise<void>;
