// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {biliClient} from '../models';

export function DownloadMusic(arg1:app.DownloadMusicParams):Promise<string>;

export function GetConfig():Promise<app.AppConfig>;

export function GetJsonOrigin(arg1:string):Promise<Array<app.MusicOrderItem>>;

export function GetSignData():Promise<biliClient.SignData>;

export function GetVideoDetail(arg1:biliClient.GetVideoDetailParams):Promise<biliClient.VideoDetailResponse>;

export function GetVideoUrl(arg1:biliClient.GetVideoUrlParams):Promise<biliClient.VideoUrlResponse>;

export function LoadSignData():Promise<biliClient.SignData>;

export function Search(arg1:biliClient.SearchParams):Promise<biliClient.SearchResponse>;

export function SetDownloadDir(arg1:string):Promise<void>;

export function UpdateClientSignData(arg1:biliClient.SignData):Promise<void>;

export function UpdateDownloadDir():Promise<string>;
