// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClientInit() {
  return window['go']['app']['App']['ClientInit']();
}

export function DownloadMusic(arg1) {
  return window['go']['app']['App']['DownloadMusic'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetJsonOrigin(arg1) {
  return window['go']['app']['App']['GetJsonOrigin'](arg1);
}

export function GetSignData() {
  return window['go']['app']['App']['GetSignData']();
}

export function GetStorage(arg1) {
  return window['go']['app']['App']['GetStorage'](arg1);
}

export function GetVideoDetail(arg1) {
  return window['go']['app']['App']['GetVideoDetail'](arg1);
}

export function GetVideoUrl(arg1) {
  return window['go']['app']['App']['GetVideoUrl'](arg1);
}

export function LoadSignData() {
  return window['go']['app']['App']['LoadSignData']();
}

export function RemoveStorage(arg1) {
  return window['go']['app']['App']['RemoveStorage'](arg1);
}

export function Search(arg1) {
  return window['go']['app']['App']['Search'](arg1);
}

export function SetDownloadDir(arg1) {
  return window['go']['app']['App']['SetDownloadDir'](arg1);
}

export function SetStorage(arg1, arg2) {
  return window['go']['app']['App']['SetStorage'](arg1, arg2);
}

export function UpdateClientSignData(arg1) {
  return window['go']['app']['App']['UpdateClientSignData'](arg1);
}

export function UpdateDownloadDir() {
  return window['go']['app']['App']['UpdateDownloadDir']();
}
