// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Search(arg1) {
  return window['go']['app']['App']['Search'](arg1);
}
